### ISSUE TITLE
Remove unnecessary files from git track

### ISSUE THREAD

**Issue by zhenik** [sysco-middleware/s2019-on-boarding-frontend#1]
@magnusihle 
I noticed several files, that should be ignored:
- `.DS_Store`
- .dockerignore it is unnecessary, because it is not in use properly. [additional info](https://forums.docker.com/t/docker-build-ignoring-dockerignore/11991)
- package-lock.json is very tricky file. You can find information that this file is important to commit, to track exact app version. But each machine on build will have different `package-lock.json` file, it creates lot of noise in PR, merges, etc...

**Comment by magnusihle** [comment]
Added the ```.DS_Store``` in ```.gitignore``` will look into the ```.dockerignore``` as well as ```package-lock.json```
